[workspace]
authors = ["Connor Stewart <connorstewarty@gmail.com>"]
channels = ["conda-forge"]
name = "connor-stewarty.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mkdocs-material = ">=9.7.0,<10"
